name: Compatibility Verification
on:
  push:
    branches:
      - main
      - '**/compat/*'
    paths-ignore:
      # - '.github/**'
      - 'gradle/**'
      - 'icons/**'
      - 'images/**'
      - '.gitignore'
      - 'README.md'
      - 'README_zh.md'
      - '.github/workflows/ide_versions_file.txt'

  pull_request:
    paths-ignore:
      - 'gradle/**'
      - 'icons/**'
      - 'images/**'
      - '.gitignore'
      - 'README.md'
      - 'README_zh.md'
      - '.github/workflows/ide_versions_file.txt'

jobs:
  compatibility:
    name:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1

      - name: Setup Java 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build the plugin using Gradle
        run: ./gradlew buildPlugin

      - name: Verify Plugin on IntelliJ Platforms
        id: verify
        uses: ChrisCarini/intellij-platform-plugin-verifier-action@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          # 需要验证的IDEA，将指定的版本放至ide_versions_file.txt文件
          ide-versions: .github/workflows/ide_versions_file.txt
          failure-levels: |
            COMPATIBILITY_PROBLEMS
            INTERNAL_API_USAGES
            MISSING_DEPENDENCIES
            INVALID_PLUGIN
            NOT_DYNAMIC

          #  COMPATIBILITY_WARNINGS 	"兼容性警告"
          #  COMPATIBILITY_PROBLEMS 	"兼容性问题"
          #  DEPRECATED_API_USAGES 	"已弃用的API"
          #  EXPERIMENTAL_API_USAGES 	"实验性API"
          #  INTERNAL_API_USAGES 	"内部API"
          #  OVERRIDE_ONLY_API_USAGES 	"仅覆盖API"
          #  NON_EXTENDABLE_API_USAGES 	"不可扩展的API"
          #  PLUGIN_STRUCTURE_WARNINGS 	"插件结构警告"
          #  MISSING_DEPENDENCIES 	"缺少依赖项"
          #  INVALID_PLUGIN 	"无效插件"
          #  NOT_DYNAMIC 	"动态插件（不重启IDE就无法加载/卸载插件）"

      # 查看输出结果，${{steps.verify.outputs.verification-output-log-filename}} 中的 verify 是上一步骤设置的 id
      - name: Get log file path and print contents
        run: |
          echo "The verifier log file [${{steps.verify.outputs.verification-output-log-filename}}] contents : " ;
          cat ${{steps.verify.outputs.verification-output-log-filename}}
